export const UPLOAD_FILE = "UPLOAD_FILE";
export const TOTAL_AMOUNT = "TOTAL_AMOUNT";
export const SPENT_BY_DAY = "SPENT_BY_DAY";
export const SHOPS_DISTRIBUTION = "SHOPS_DISTRIBUTION";
export const CATEGORY_DISTRIBUTION = "CATEGORY_DISTRIBUTION";
export const TIME_RANGE = "TIME_RANGE";
export const MONTHLY_EXPENSE = "MONTHLY_EXPENSE";
export const SET_MONTHS = "SET_MONTHS";
